### ISSUE TITLE
Modifier un utilisateur

### ISSUE THREAD

**Issue by cchampou** [cchampou/protec-admin#3]
En tant que cadre
Je souhaite pouvoir créer modifier un utilisateur
--
## Règles métiers

1. je dois pouvoir modifier l'ensemble des champs suivant :

- Nom
- Prénom
- Email
- Numéro de téléphone
- Rôle : Deux valeur => Secouriste / Cadre (Par défaut mettre secouriste)

2. L'ensemble des champs sont obligatoires. Si un champ n'est pas renseigné, afficher un message d'erreur : Le champ <nom_champ> est obligatoire (Ex : Le champ prénom est obligatoire)
3. L'email doit correspond au format email.
4. L'email doit être unique
5. Le téléphone doit correspond au format téléphone français.

**Comment by cmoysan** [comment]
JE vois toujours le terme Enregistrement effectué comme tu voir dans mon imprime écran

![Image](https://user-images.githubusercontent.com/1431054/210366176-737dd370-49c2-4531-bc51-15f9e1a93fdf.PNG)

**Comment by cchampou** [comment]
> JE vois toujours le terme Enregistrement effectué comme tu voir dans mon imprime écran
> 
> ![Image](https://user-images.githubusercontent.com/1431054/210366176-737dd370-49c2-4531-bc51-15f9e1a93fdf.PNG)

Corrigé :checkered_flag:

**Comment by cmoysan** [comment]
**Ok pour moi.**
