### ISSUE TITLE
EVENEMENT - Afficher la date et l'heure au bon fuseau horaire

### ISSUE THREAD

**Issue by cchampou** [cchampou/protec-admin#7]
La date et heure de début et de fin sont enregistrées sous le fuseau UTC.

Comportement voulu : Affichage de la date et heure de début et la date et heure de fin sous le fuseau de Paris à l'ensemble des endroits gérés (liste sur la page cadre, liste des événements et détail d'un événement au sein de l'appli et à la modification de l'application).

Le format attendu qui doit être affiché : `dd/mm/YYYY à hh:mm`

**Comment by cchampou** [comment]
J'ai pris la liberté de formater le mois en toute lettre, je trouve que cela rend encore plus digeste. Qu'en penses-tu ?

**Comment by cmoysan** [comment]
Ok pour afficher en toute lettre le mois. Par contre tu ne l'as pas fait sur l'app est-ce normal ?

**Comment by cmoysan** [comment]
@cchampou

**Comment by cmoysan** [comment]
Sinon test ok.

**Comment by cchampou** [comment]
> Ok pour afficher en toute lettre le mois. Par contre tu ne l'as pas fait sur l'app est-ce normal ?

Dans l'app vu que c'est pas le meme langage / lib faut que je trouve comment faire. Tu trouves ça mieux, je fais ca dans l'app aussi ?

**Comment by cmoysan** [comment]
Oui je me doute bien, c'est pour ça que pour l'instant en beta, j'ai envie de dire ne nous embêtons pas.
