### ISSUE TITLE
Statistiques - Affichage du nombre de secouristes qui n'ont pas encore répondu

### ISSUE THREAD

**Issue by cchampou** [cchampou/protec-admin#9]
En tant que cadre
Je souhaite que la statat au sein du cadre en attente, contienne uniquement les personnes qui n'ont pas encore répondu à l'événément (les gens qui n'ont pas encore consulté + les gens qui n'ont pas répondu)
Afin de me permettre d'améliorer mon suivi, et de savoir si je dois passer à l'étape suivant de notification.

**Comment by cmoysan** [comment]
Ok pour moi.
